layout_spectrum: 0.437276
color:
  saturation: 0.7168459
  lightness: 1
  brandStrength: 0.7585618
  brandColors:
    - '#151517'
    - '#F4F5F3'
    - '#CFCFBC'
    - '#646466'
    - '#D0A390'
  rhythmicContrast: 0.421147
typography_spectrum: 0.1863037
name: Virus999
