layout_spectrum: 0.437276
name: Virus999
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
typography_spectrum: 0.5151771
color:
  brandStrength: 0.7585618
  saturation: 0.7168459
  brandColors:
    - '#151517'
    - '#F4F5F3'
    - '#CFCFBC'
    - '#646466'
    - '#D0A390'
  lightness: 1
  rhythmicContrast: 0.421147
