color:
  saturation: 0.7168459
  brandStrength: 0.7585618
  rhythmicContrast: 0.421147
  brandColors:
    - '#151517'
    - '#F4F5F3'
    - '#CFCFBC'
    - '#646466'
    - '#D0A390'
  lightness: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.437276
typography_spectrum: 0.1863037
name: Virus999
